<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>10</LangVersion>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4535" />
  </ItemGroup>

</Project>
